-- This script was generated by Navraj Narula
-- on May 1, 2016 at 7:50 PM.

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MassReversals
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MassReversals
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MassReversals` DEFAULT CHARACTER SET utf8 ;
USE `MassReversals` ;

-- -----------------------------------------------------
-- Table `MassReversals`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MassReversals`.`Person` (
  `PersonID` INT NOT NULL,
  `LastName` VARCHAR(100) NULL,
  `FirstName` VARCHAR(100) NULL,
  `Position` VARCHAR(80) NULL,
  PRIMARY KEY (`PersonID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MassReversals`.`Case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MassReversals`.`Case` (
  `CaseID` VARCHAR(40) NOT NULL,
  `CaseName` VARCHAR(200) NULL,
  `DateDecided` DATE NULL,
  `DateArgued` DATE NULL,
  `DateFiled` DATE NULL,
  PRIMARY KEY (`CaseID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MassReversals`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MassReversals`.`Status` (
  `CaseID` VARCHAR(40) NOT NULL,
  `Cause` VARCHAR(300) NULL,
  `RevReason` VARCHAR(300) NULL,
  `Disposition` VARCHAR(40) NULL,
  `Status` VARCHAR(40) NULL,
  PRIMARY KEY (`CaseID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MassReversals`.`Proceedings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MassReversals`.`Proceedings` (
  `CaseID` VARCHAR(40) NOT NULL,
  `TrialCourt` VARCHAR(65) NULL,
  `AppCourt` VARCHAR(65) NULL,
  `County` VARCHAR(45) NULL,
  PRIMARY KEY (`CaseID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MassReversals`.`CasePerson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MassReversals`.`CasePerson` (
  `PersonID` INT NOT NULL,
  `CaseID` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`PersonID`, `CaseID`),
  INDEX `CaseID_idx` (`CaseID` ASC),
  CONSTRAINT `PersonID`
    FOREIGN KEY (`PersonID`)
    REFERENCES `MassReversals`.`Person` (`PersonID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CaseID`
    FOREIGN KEY (`CaseID`)
    REFERENCES `MassReversals`.`Case` (`CaseID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
